etls:
  SalesSync:
    source:
      type: mysql
      dbClient: EtlSavePoint
    transformer:
      type: SalesSync
      transformerOptions:
        name: test
    destination:
      type: jsonfile
      directory: /tmp
      fileName: SalesSync.js 
    savepoint:
      type: mysql
      dbClient: EtlSavePoint

mysql:
  EtlSavePoint:
    master:
      connectionConfig:
        host: localhost
        # port: 3306
        user: root
        password: hipages
        database: qbo
    slave:
      connectionConfig:
        host: localhost
        # port: 3306
        user: root
        password: hipages
        database: qbo
