etls:
  SalesSync:
    source:
      type: SalesSync
      dbClient: EtlSavePoint
      sourceOptions: 
        fileDir: csv/
    transformer:
      type: SalesSync
      transformerOptions:
        name: test
    destination:
      type: SalesSync
      destinationOptions:
        consumerKey: Q0ACHcPD7nTuKQyUNfjIpId3tT17vR4wwaNIYhqbFBUPCUA5ub
        consumerSecret: DJTIiIusl6jSOMuARX6JgKJiyS1motzJwCMsm80q
        oauthToken: eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..Iz6XnvN65u8JYTleYyge9w.ruhwwzNtSnddaiFjzR64BEqowqtLRbiZfKaUDBfIIUzV3rJQbIv_-OxPMXDhkvxfoE8wz1kUhTyRwGoHxJP0CchqZIefpUnO_R8pwbEr_Uz4YGiiBVU06kHALgVMxgz3xc40FF8f6voR4N4VtV6zTWUWeV7TvtAU3C40hejpqMkB8JnNLOU08CQ9JLK4Dj-M8y38Fylc6W-7tB9DJX_6dfXzUDUzn5XXkGVhnPgBUtnlHNtabVfj48M_Lfzgt-pQTh04783s9qnDbvPQHOz5QACghI4FONXL2HoZlqrv8dW3RvYRV4FLebGDDEBdvPDepVwL6CCOv8EsFQ3F-UhIdP75fwtCb0KxHSdEi1HEup84N7LxWJxzqgDfVI1uPE2irxWgnw4of1kRSIQ0qouyU6qLcjRpNXlBjKa5hZ_aDQ6yE9I_GUXECeDRez4YtkTOu7BfnU76I6rqYY5g2DY8g9VWxiOD-yRJnGFPkr3jbIIqo4T8VnrWSbCtVOCpRGVgy4l5Diu72RsyPlm-6EuzqftM8-kH7-luJikWSF2mO_Dg4xClk64CkySe_xwZA8EELp4mMsSCvFB25te9rGqbcFIPTts34FVAYNTt3-ZdIl_WnNFp9nA6YYwJQS-s3CT7rSfSOQseFym0EK2cGJz4pDVLoq8A5leTkUTjV4_kATXMQIGcrKpJhL6Jw5yuDVYC.W5wCc_uAxUePHt8f4-nQWQ
        oauthTokenSecret: UTBBQ0hjUEQ3blR1S1F5VU5maklwSWQzdFQxN3ZSNHd3YU5JWWhxYkZCVVBDVUE1dWI6REpUSWlJdXNsNmpTT011QVJYNkpnS0ppeVMxbW90ekp3Q01zbTgwcQ==
        realmId: 193514693719789
        userSandbox: true
        debug: true
        minorversion: 8
    savepoint:
      type: mysql
      dbClient: EtlSavePoint

mysql:
  EtlSavePoint: # this is the name of the object that will be exposed in the context
    master:
      max: 10
      min: 1
      idleTimeoutMillis: 20000
      maxWaitingClients: 10
      connectionConfig:
        charset: utf8
    slave:
      max: 10
      min: 1
      idleTimeoutMillis: 20000
      maxWaitingClients: 10
      connectionConfig:
        charset: utf8
Context:
  ActiveProfiles: production
