app:
  name: trench
  validEtls:
    - test_1

generalConfig:
  source:
    maxRetries: 3
    timeoutMillis: 5000
  transformers:
    minSuccessPercentage: 1
    timeoutMillis: 5000
  destinations:
    maxRetries: 3
    timeoutMillis: 5000
    batchSize: 1

etls:
  test_1:
    savepoint: 
      type: 'static'
      savepoint: '{"lastRunStartTime":"2017-09-26T23:57:13.560Z"}'
    source: 
    transformer:      
    destination:
logging:
  streams:
    console:
      type: console
    myredis:
      type: redis
      host: logstash-redis.devops.svc.cluster.local
    mainLogFile:
      type: file
      path: main.log
  loggers:
    - name: ROOT
      streams:
        console: error
        #myredis: debug
        mainLogFile: error